### ISSUE TITLE
Modifying indentifierUris as documented results in error

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#1717]
Following instruction 5 of the [docs](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-1-configure-an-application-in-azure-ad), I update my app manifest with the following values:
```json
"identifierUris" : [                                
        "https://onestore.microsoft.com",
        "https://onestore.microsoft.com/b2b/keys/create/collections",
        "https://onestore.microsoft.com/b2b/keys/create/purchase"]
```
When attempting the save the manifest, the following error is returned.
**“Failed to update WindowsTestApp application. Error detail: The Application ID URI must be from a verified domain within your organisation's directory.”**  
Per the docs [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest) ```identifierUris``` are for apps that reside in the tenant. These 'onestore' services obviously do not reside in my tenant. What should I populate identifierUris with?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#feedback)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by MoonCha** [comment]
I have the same problem. Is there anybody solved this?

**Comment by bronze1man** [comment]
I have solve this problem:
Changing following fields to following value in your manifest.
```
"accessTokenAcceptedVersion": 1,
"identifierUris": [
    "https://onestore.microsoft.com",
    "https://onestore.microsoft.com/b2b/keys/create/collections",
    "https://onestore.microsoft.com/b2b/keys/create/purchase"
    ],
"signInAudience": "AzureADMyOrg",
```
The "signInAudience" part can solve this problem, and the "accessTokenAcceptedVersion" part can solve the "getCustomerCollectionsIdAsync" return empty problem.
https://stackoverflow.com/a/56848128/1586797

**Comment by dontspeak** [comment]
Is this really the solution? Sorry, but I cant believe that MS does not update its documentation or resolves the bug (if any). 

By the way, this does not work, as the error that appears then is:  Another object with the same value for property identifierUris already exists. [LsUND]

**Comment by Joel-Intact** [comment]
Greetings, any update on this issue?

The onestore.microsoft.com URIs still cannot be added to the identifierUris in the appReg manifest.  Guidance on this would be most appreciated.

`"identifierUris" : [                                
        "https://onestore.microsoft.com",
        "https://onestore.microsoft.com/b2b/keys/create/collections",
        "https://onestore.microsoft.com/b2b/keys/create/purchase"
    ],`

**Comment by CameronGoodwin** [comment]
Hi,
I also ran into this when writing some samples.  The error was happening because there is another app that has already defined those identifierURI's under your AAD tenant.  But it only needs to be defined under one app and other apps under the same tenant don't need to re-define them in their manifests.  You can create another app / client ID in AAD under the tenant that doesn't have the identifierURI's the docs say you need and it will work to get the right token / Store ID.   

I did this with my sample where another client had already defined them and hit this error.  I just went ahead anyways with the rest of the setup docs and got it working requesting the right authorization / bearer tokens.  Just know that for the commerce ones, I had to re-publish my app to the store before I started to see results otherwise I was just seeing blank results.

Hope that helps.

**Comment by GrantMeStrength** [comment]
Sorry for the delay is getting to this issue. We are investigating.

**Comment by DmitriiKh** [comment]
I am getting an error as well. It says "Failed to update PdfOnlineConvertorServiceAD application. Error detail: Application alias 'url' value is invalid. [95Rhd74KVtnJBw7SyhbTCP]"

**Comment by 10-20media** [comment]
We are also experiencing this error when adding the identifierUris specified in documentation: "...Application alias 'url' value is invalid". This is hindering us from deploying our UWP app as there will be no clear way to validate customer purchases and provide support. Is there an alternative or workaround that is available? Note that this is the only application for this AAD tenant.

Thanks.

**Comment by CameronGoodwin** [comment]
> We are also experiencing this error when adding the identifierUris specified in documentation: "...Application alias 'url' value is invalid". This is hindering us from deploying our UWP app as there will be no clear way to validate customer purchases and provide support. Is there an alternative or workaround that is available? Note that this is the only application for this AAD tenant.
> 
> Thanks.

I am on one of the teams that supports partners here at Microsoft and I have multiple partners also having issues adding these to their manifests for new apps.  This seems to still be working for apps or tenants that already have them defined, but new apps can't.  I'm not the ones trying to fix it, but I am watching the internal threads and hoping we can get this resolved.  But I don't have an ETA right now.

**Comment by pavelkouril** [comment]
Yes, we are hitting this issue as well.

Also, having these entries in manifest forbids you to create a new client secret - so we removed them temporarily, hoping we could generate a new client secret and add them back later, but then we stumbled upon the inability to add the lines back again. :/

The solution written in https://github.com/MicrosoftDocs/windows-uwp/issues/1717#issuecomment-507577676 does not work, unfortunately.

**Comment by CameronGoodwin** [comment]
Hi all, @pavelkouril @10-20media @DmitriiKh @Joel-Intact 
We are trying out a fix for the Collections endpoints.  You don't have to update your manifest anymore.  You should just be able to request the needed access tokens for the https://onestore.microsoft.com and https://onestore.microsoft.com/b2b/create/Collections identifierURI's.  

For those affected can you check that you can now get the token for https://onestore.microsoft.com/b2b/create/collections?  We haven't updated to enable the purchase one yet.

**Comment by pavelkouril** [comment]
@CameronGoodwin We just tried a test purchase in the app and it's validation on our backend services using the collections endpoint, and it seems to work properly in our use-case.

Thank you!

**Comment by DmitriiKh** [comment]
I confirm that we can get the access tokens for both https://onestore.microsoft.com and https://onestore.microsoft.com/b2b/create/Collections now. Thanks!

**Comment by 10-20media** [comment]
@CameronGoodwin We were able to get access tokens using the provided endpoints. Thank you for updating this!

**Comment by hickeys** [comment]
Looks like this issue has been resolved. Closing.

**Comment by mjfusa** [comment]
This may be fixed but the documentation still leads to an error. (The first entry in this issue.)

**Comment by combinatorial** [comment]
Yep, the documentation is wrong and leads wasted time for developers.

**Comment by 10-20media** [comment]
Not to beat this thread to death but @CameronGoodwin, do you have a timeframe on when the purchase endpoint might work for access tokens? This is now causing issue for subscription products for us. Thanks!

**Comment by Chris1-Fu** [comment]
Hi @CameronGoodwin , I have the same issue of the purchase one.
Can I know when the purchase endpoint can be used? Thanks!

**Comment by CameronGoodwin** [comment]
@10-20media and @Chris1-Fu 
Rest assured you are not beating the thread to death, it helps that you are vocalizing the issues you are having as well so that I can continue to push for the correct fixes.  I was away for extended time off during the Holidays and also the teams I have been working with were also not in a position to make additional changes until after the Holidays.

Now that I am back online and they should be too rest assured I will be pushing for the Purchase endpoint as well.  I need that for the other partners that I'm working directly with as well.

**Comment by Zofware** [comment]
Thanks @CameronGoodwin for working on this. I would love to use the purchase endpoint too.

**Comment by CameronGoodwin** [comment]
The ones that I am working with are hoping that maybe we will have something working next week.  So I will keep on this as they are and get back to everyone when it is up.

**Comment by 10-20media** [comment]
Great news! Thank you for the update!

**Comment by hickeys** [comment]
I've updated the code in the article based on this conversation. The changes should be published shortly.

**Comment by CameronGoodwin** [comment]
Thanks @hickeys !

**Comment by CameronGoodwin** [comment]
@10-20media @Zofware @Chris1-Fu 
It appears that you can now get the proper keys for the purchase endpoints.  I was able to request one for the b2b/create/purchase URI just now, however I haven’t done an end to end test using this token in a flow to auth with one of the purchase services yet as some of my tools need to be updated and re-configured to use my non-MS AAD to simulate external partners.  But this is a good sign that we are no longer getting an HTTP 400 error :)

Give it a try on your end and let me know if you run into any issues.

**Comment by Zofware** [comment]
@CameronGoodwin I can confirm that it's working now. I used Postman to get a `purchase` endpoint token and it succeeded. I'll test the APIs using that token later today when I have the time and report any issues I find. Thanks so much to you and the team for fixing this!

**Comment by Zofware** [comment]
FWIW, I have none of the microsoft.com URIs in my `identifierUris` array. The only URI I have listed there is one using my own custom domain. I'm still unable to add the microsoft.com URIs to my manifest. Maybe that's all by design but last time I checked the docs still said you needed to add them.

**Comment by Zofware** [comment]
`StoreContext.GetCustomerPurchaseIdAsync` is returning an empty string for me when I use the `purchase` endpoint token. I don't see any errors or exceptions in the debugger output window. Thoughts @CameronGoodwin?

**Comment by Zofware** [comment]
I tried again to add the microsoft.com URIs to the array in my application's manifest but the manifest editor still won't let me.
![image](https://user-images.githubusercontent.com/51502102/104777910-5e2db580-5731-11eb-8290-f753e5500c49.png)

**Comment by combinatorial** [comment]
per Cameron's comment above...

> We are trying out a fix for the Collections endpoints. You don't have to update your manifest anymore. 

We can confirm this is true. Both purchase and collections endpoint are returning an access token without the manifest updates.

**Comment by Zofware** [comment]
Thanks @combinatorial. Now that you can get purchase tokens, can you confirm that you can successfully get a user store id back from `StoreContext.GetCustomerPurchaseIdAsync`? I just get an empty string when I call it. Thanks.

**Comment by combinatorial** [comment]
> Thanks @combinatorial. Now that you can get purchase tokens, can you confirm that you can successfully get a user store id back from StoreContext.GetCustomerPurchaseIdAsync? I just get an empty string when I call it. Thanks.

I cannot yet confirm that, as we haven't coded it up. We were waiting for the token endpoint to work before we moved on to the next step. I will report back next week.

**Comment by CameronGoodwin** [comment]
I am still working on getting my in-progress sample up on its feet after the holiday break but I will try and confirm here when I get it running.

**Comment by Zofware** [comment]
I tried it again just now and this time I got a non-empty user store id back from `StoreContext.GetCustomerPurchaseIdAsync`. Let me see if I can do anything with it...

**Comment by Zofware** [comment]
I was able to use the [recurrences query](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-subscriptions-for-a-user) to list subscriptions so hopefully this means everything else will work too! Next I'll try [canceling and refunding](https://docs.microsoft.com/en-us/windows/uwp/monetize/change-the-billing-state-of-a-subscription-for-a-user) subscriptions.

**Comment by CameronGoodwin** [comment]
I just got my own sample up and running and I was able to get the UserPurchaseID and use it in a call to the https://purchase.mp.microsoft.com/v8.0/b2b/orders/query endpoint.  I then make a purchase and called it again, the new item purchased was reflected as expected.  

I was getting the error 0x803f6107 from the API initially which is a generic store error, but it usually means that the package you are running doesn't have a valid License to go off of when you are doing development out of the GDK.  I fixed it so that it was using a real token from the store and am not having issues anymore.  

So it should be working. :)

**Comment by Zofware** [comment]
Yeah things are looking pretty good. Thanks @CameronGoodwin! I was able to successfully turn off auto-renew, cancel, and refund subscriptions just fiddling around with the API in Postman.

The only funny thing was I must have hit a rate limit or something with the auto-renew toggle. I turned it off via the API, then turned it on via my Microsoft Account on the web, then back off via the API but then I was no longer able to turn it back on via the web. I kept getting a "something went wrong" error screen.

**Comment by 10-20media** [comment]
I was able to load a token, get an appropriate Store ID Key and successfully query the recurrences endpoint. I haven't had a chance to go through the various subscriptions tests yet but so far so good. Thank you so much @CameronGoodwin!

**Comment by Chris1-Fu** [comment]
@CameronGoodwin 
I was able to get the purchase store ID key, and I try to get subscriptions info, change the billing state of a subscription, these methods all succeeded. Thanks for fixing it!

**Comment by CameronGoodwin** [comment]
Wanted to hopefully provide some helpful information to those who were following this thread or may find it later.

We just released a GitHub repository that provides the Microsoft.StoreServices namespace that helps manage the authentication keys, tokens, and call the Microsoft Store Services from your own services.  Feel free to provide feedback on that github and hopefully this makes integrating with the AAD Auth flow for commerce services easier.

I plan to make this into a NuGet package as well, but have to do some configuration on my side before I can officially release that on NuGet.  Till then, you can pull down the repo and compile the namespace into your project.  A sample will also be coming in the near future, we just haven't setup the reserved GitHub and configuration for it yet.

https://github.com/microsoft/Microsoft-Store-Services/
