### ISSUE TITLE
"Get response info for reviews" endpoint broken

### ISSUE THREAD

**Issue by tipa** [MicrosoftDocs/windows-uwp#4389]
This endpoint is broken since several weeks. It always returns error code 400 (Bad Request).

I am sending the request as documented (incl the Bearer auth token in the request headers): 
GET https://manage.devcenter.microsoft.com/v1.0/my/reviews/REVIEW_ID_GUID/apps/APP_ID/responses/info 

There is no response body, just this:
![image](https://user-images.githubusercontent.com/2863198/233368538-e3783088-267d-4103-afc6-e8983565b4ec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06bc1ae3-fc61-3855-fdf8-4da6b5333662
* Version Independent ID: 311ca114-a488-2761-46c7-2d6bbe639c2a
* Content: [Get response info for reviews - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/get-response-info-for-app-reviews)
* Content Source: [uwp/monetize/get-response-info-for-app-reviews.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/get-response-info-for-app-reviews.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by tipa** [comment]
Still broken. Any updates? @Karl-Bridge-Microsoft @hickeys

**Comment by hickeys** [comment]
@tipa    

I'll check with the engineering team and see if there have been any changes recently. In the meantime, can you post the request you're sending? (remove any sensitive info)

**Comment by tipa** [comment]
Thanks - it's just a simple GET request with the auth Bearer Header:
![image](https://user-images.githubusercontent.com/2863198/237004578-d9a48819-4f74-4605-8260-6f001dc8bd23.png)

**Comment by hickeys** [comment]
Thanks @tipa.

I've reached out to the team and asked them to investigate the source of the errors you're seeing. I'll update when I hear back.

**Comment by tipa** [comment]
@hickeys any updates? The endpoint is still broken

**Comment by tipa** [comment]
Still broken... :(
Seems like I am the only one using this API

**Comment by tipa** [comment]
The API now returns a `502 (Bad Gateway)` but this enpoint remains broken

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.

**Comment by tipa** [comment]
Oh nice - another "just close all the open issues with a copy-paste response" instead of actually _fixing_ the issues, as we've seen in other Microsoft-owned repositories.


> and there's a good chance your problem has been addressed

The issue has not been adressed


> but if you feel it is still valid and has not been addressed, please re-open it with any more available information

the issue is still valid. I can not re-open this issue. All the needed information can be read in my previous comments
